version: '2'

services:

        app-java:       
                image: java-app
                depends_on:
                        - mysql-db
                links:
                        - mysql-db

        mysql-db:
                image: mysql
                volumes: 
                - ./Mysql/mysql-dump:/docker-entrypoint-initdb.d
                environment:
                        - MYSQL_PASSWORD=password
                        - MYSQL_ROOT_PASSWORD=password
networks:
        default:
               external:
                       name: dev-network
