version: '2'
services:
        mysql-db:
                image: mysql
                volumes: 
                - ./Mysql/mysql-dump:/docker-entrypoint-initdb.d
                environment:
                        - MYSQL_PASSWORD=password
                        - MYSQL_ROOT_PASSWORD=password


